### ISSUE TITLE
was v1.3.4 retagged?

### ISSUE THREAD

**Issue by petere** [omniti-labs/mimeo#12]
My records show https://github.com/omniti-labs/mimeo/archive/v1.3.4.zip with sha1 9063ba35dea4b9121850392bf181f978d745fc12 on March 5.

But now this was apparently repackaged around April 14 with different contents.

Could you clarify that, and make a new tag possibly?

**Comment by keithf4** [comment]
Yes, it was retagged. I'd renamed the `doc/howto.md` to `doc/howto_mimeo.md` due to it conflicting with the howto file in pg_partman. Was causing some packaging systems to break because they would try and put the two files with the same name in the doc folder during installation.

Didn't realize that would cause issues, sorry. Any suggestions on how you have you retagged things like this in other projects when the version hasn't actually changed?

**Comment by petere** [comment]
If you change something, you should make a new release. They're cheap. ;-)

See git-tag man page under "On Re-tagging" for discussion.

**Comment by petere** [comment]
At this point it's too late to make a new release. I'm satisfied with this explanation if you want to close this issue.

**Comment by keithf4** [comment]
Thanks! Will keep this in mind for next time. :)
