### ISSUE TITLE
Source table in Read-Only Streaming Replication Slave server

### ISSUE THREAD

**Issue by isaiasanchez** [omniti-labs/mimeo#15]
I'm having problems with a snapshot when source table is from Pg 9.2 slave server using streaming replication. Always says "NOTICE:  Remote table has not had any writes. Skipping data pull", and it's a table with lots of insert mostly. I dunno if the slave cannot see the insertions in master server.

I also have some snapshots using an pg 9.4 Slave (with replication slot) and I don't have this issue.

**Comment by keithf4** [comment]
I'm honestly more surprised that it works in 9.4 than that it doesn't work in 9.2. I check the table statistics (pg_stat_all_tables) to see if there have been any inserts, updates or deletes or the table since the last time it ran. To my knowledge, those do not get replicated to the slave.
I'll see if I can make an option for snapshot replication to ignore the table stats and always replicate. I agree you should be able to do that from a slave.

**Comment by isaiasanchez** [comment]
I'm also facing another issue. When the source is the father of a partition set, probably these statistics are zero for father table but not children. What are you suggesting can help in this case too.

**Comment by keithf4** [comment]
I would imagine a partitioned table would not be a good source for a snapshot table. Snapshots are meant for smaller tables or larger ones that are rarely written to. Partitioned tables, in my experience, are usually neither of these. I would recommend looking at the incremental replication methods if they're partitioned by time or id. Otherwise, I believe DML replication works on a partitioned source, but I'd have to test that out to be sure.

**Comment by isaiasanchez** [comment]
I am using snapshot because:
1. I only need an small portion, so I use p_condition to limit that.
2. Over incremental because there are lot of delete/insert then incremental id have lot of "gaps".
3. Over DML because I am not allowed to add triggers to the source.

I didn't know the limitation. Now I just remove it from mimeo and add it to postgres_fdw.

**Comment by keithf4** [comment]
Ok. That makes sense for a partial data set.
The option to ignore stats should work in that case then too I think. Don't have an ETA one when I'll get that new feature in, but I am working on fixing something else now so hopefully won't be too long.

**Comment by keithf4** [comment]
In v1.4.0, there is now a parameter to the `refresh_snap()` function as well as a new column in the `refresh_config_snap` table to tell mimeo to always refresh a snap table no matter what the statistics say. Set `check_stats` to false to tell it to ignore the source statistics.

Let me know if it works ok for you.

**Comment by isaiasanchez** [comment]
I just update to 1.4.0 and now I'm not able to create new snapshots:

select  mimeo.snapshot_maker('public.my_org_table',1,'public.my_dst_table');
ERROR:  query string argument of EXECUTE is null

**Comment by isaiasanchez** [comment]
I just add FALSE by default in v_jobmon 'cause I don't use that extension.

v_jobmon                    boolean := FALSE;

probably you have a better solution.

I tested on slave sever and partitioned tables and it's working BTW.

**Comment by keithf4** [comment]
Yeah, there's a bug I'm working on fixing. The maker functions are not working if pg_jobmon is not installed. I should have a fix out this week. Your solution works for now.

**Comment by keithf4** [comment]
The bug with the maker functions has been fixed in version 1.4.1. 
Let me know if things are working ok for you know.

**Comment by isaiasanchez** [comment]
should I use the master? there isn't 1.4.1 tag.

**Comment by keithf4** [comment]
New tag has been pushed.

**Comment by isaiasanchez** [comment]
all works fine now.
